# Generated by Django 3.0 on 2020-01-03 08:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Landlord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('social_security_number', models.CharField(max_length=255)),
                ('email_address', models.EmailField(max_length=254)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='rentalProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_property_listing', models.CharField(choices=[('APARTMENT', 'Apartment'), ('HOLIDAY_HOME', 'Holiday home'), ('SINGLE_FAMILY_HOME', 'Single family home'), ('COMMERCIAL', 'Commercial')], default='APARTMENT', max_length=50)),
                ('type_of_building_choices', models.CharField(choices=[('CONDOMINIUM', 'Condominium'), ('ROW_HOUSE', 'Row house'), ('SINGLE_FAMILY_HOUSE', 'Single family house'), ('HOLIDAY_HOME', 'Holiday_home'), ('DUPLEX', 'Duplex'), ('SINGLE_FAMILY_HOME_COOP', 'Single family home(CO-OP)'), ('CONDOMINIUM_EXTERNAL_ENTRANCE', 'Condominium external entrance'), ('WOODEN_COMDOMINIUM_HOUSE', 'Wooden condominium house')], default='CONDOMINIUM', max_length=50)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rentalProperties', to=settings.AUTH_USER_MODEL)),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rental_app.Landlord')),
            ],
        ),
        migrations.CreateModel(
            name='rentalImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apartment_pictures', models.ImageField(upload_to='')),
                ('rentalProperty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='images', to='rental_app.rentalProperty')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=255)),
                ('borough', models.CharField(max_length=255)),
                ('postal_code', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=50)),
                ('province', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('rental_property', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='location', to='rental_app.rentalProperty')),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_rental_terms', models.CharField(choices=[('PERMANENT', 'permanent'), ('FiXED', 'fixed')], default='PERMANENT', max_length=20)),
                ('rent_availability', models.DateField()),
                ('rent_availability_info', models.TextField()),
                ('rent_per_month', models.IntegerField()),
                ('deposit_for_rent', models.IntegerField()),
                ('deposit_for_rent_info', models.TextField()),
                ('rental_increment', models.IntegerField()),
                ('index_value', models.IntegerField()),
                ('index_date', models.DateField()),
                ('rent_electricity', models.CharField(choices=[('UNDEFINED', 'undefined'), ('INCLUDED_IN_THE_RENT', 'included in the rent'), ('RESPONSIBILITY_OF_TENANT', 'responsibility of tenant'), ('FIXED_FEE', 'fixed fee'), ('OTHER', 'other')], default='UNDEFINED', max_length=50)),
                ('electricity_fixed_fee', models.IntegerField()),
                ('water_fee', models.CharField(choices=[('UNDEFINED', 'undefined'), ('INCLUDED_IN_THE_RENT', 'included in the rent'), ('RESPONSIBILITY_OF_TENANT', 'responsibility of tenant'), ('FIXED_FEE_PER_PERSON', 'fixed fee per person'), ('OTHER', 'other')], default='UNDEFINED', max_length=50)),
                ('water_fee_per_person', models.IntegerField()),
                ('heating_fee', models.CharField(choices=[('UNDEFINED', 'undefined'), ('INCLUDED_IN_THE_RENT', 'included in the rent'), ('RESPONSIBILITY_OF_TENANT', 'responsibility of tenant'), ('FIXED_FEE', 'fixed fee'), ('OTHER', 'other')], default='UNDEFINED', max_length=50)),
                ('heating_fixed_fee', models.IntegerField()),
                ('Other_cost', models.TextField()),
                ('pets_allowed', models.BooleanField(default=True)),
                ('smoking_allowed', models.BooleanField(default=True)),
                ('insurance_required', models.BooleanField(default=True)),
                ('other_terms', models.TextField()),
                ('rental_property', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='rental_app.rentalProperty')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ApartmentBasicInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('living_area', models.IntegerField()),
                ('number_of_rooms', models.IntegerField()),
                ('floors', models.IntegerField()),
                ('furnished', models.BooleanField(default=True)),
                ('type_of_kitchen_choices', models.CharField(choices=[('UNKNOWN', 'Unknown'), ('NO_KITCHEN', 'No kitchen'), ('KITCHEN', 'Kitchen'), ('MINI_KITCHEN', 'Mini kitchen'), ('OPEN_KITCHEN', 'Open kitchen')], default='UNKNOWN', max_length=50)),
                ('sauna', models.BooleanField(default=True)),
                ('balcony', models.BooleanField(default=True)),
                ('apartment_layout_type', models.IntegerField()),
                ('apartment_condition', models.CharField(choices=[('EXCELLENT', 'excellent'), ('GOOD', 'good'), ('FAIR', 'fair'), ('POOR', 'poor'), ('VERY_BAD', 'very bad')], default='EXCELLENT', max_length=50)),
                ('apartment_conditions_freetext', models.TextField()),
                ('rental_property', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='basic_info', to='rental_app.rentalProperty')),
            ],
        ),
    ]
