# Generated by Django 3.0 on 2020-01-14 08:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rental_app', '0002_auto_20200113_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalproperty',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rentalProperties', to=settings.AUTH_USER_MODEL),
        ),
    ]
