# Generated by Django 3.0 on 2020-01-16 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_app', '0005_auto_20200116_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalimages',
            name='video',
            field=models.URLField(max_length=250),
        ),
    ]
