# Generated by Django 3.0 on 2020-01-20 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rental_app', '0006_auto_20200116_0857'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentalimages',
            name='rentalProperty',
        ),
        migrations.AddField(
            model_name='apartmentbasicinfo',
            name='apartment_pictures',
            field=models.ImageField(default=1, upload_to='images'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apartmentbasicinfo',
            name='video',
            field=models.URLField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rentalproperty',
            name='borough',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rentalproperty',
            name='city',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rentalproperty',
            name='country',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rentalproperty',
            name='postal_code',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rentalproperty',
            name='province',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rentalproperty',
            name='street',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='apartmentbasicinfo',
            name='rental_property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='basic_info', to='rental_app.RentalProperty'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='rental_property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='rental_app.RentalProperty'),
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='rentalImages',
        ),
    ]
