# Generated by Django 3.0 on 2020-01-24 08:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rental_app', '0007_auto_20200120_0932'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartmentbasicinfo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='apartmentbasicinfo',
            name='rental_property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='basic_info', to='rental_app.RentalProperty'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='rental_property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='rental_app.RentalProperty'),
        ),
        migrations.AlterField(
            model_name='landlord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='landlords', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rentalproperty',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rentalproperty', to=settings.AUTH_USER_MODEL),
        ),
    ]
