# Generated by Django 3.0 on 2020-01-29 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rental_app', '0008_auto_20200124_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartmentbasicinfo',
            name='apartment_layout_type',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='apartmentbasicinfo',
            name='floors',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='apartmentbasicinfo',
            name='living_area',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='apartmentbasicinfo',
            name='number_of_rooms',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='apartmentbasicinfo',
            name='rental_property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='basic_info', to='rental_app.RentalProperty'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='rental_property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='rental_app.RentalProperty'),
        ),
    ]
