# Generated by Django 3.0 on 2020-01-31 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rental_app', '0009_auto_20200129_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartmentbasicinfo',
            name='rental_property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='basic_info', to='rental_app.RentalProperty'),
        ),
        migrations.AlterField(
            model_name='apartmentbasicinfo',
            name='title',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='Other_cost',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='deposit_for_rent_info',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='index_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='index_value',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='other_terms',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='rent_availability_info',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='rental_increment',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='rental_property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='rental_app.RentalProperty'),
        ),
    ]
