# Generated by Django 3.0 on 2020-01-31 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rental_app', '0010_auto_20200131_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartmentbasicinfo',
            name='rental_property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='basic_info', to='rental_app.RentalProperty'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='rental_property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='rental_app.RentalProperty'),
        ),
    ]
